### ISSUE TITLE
不能正确停止程序

### ISSUE THREAD

**Issue by PupilStudio** [ImFatFish/pySetuGetter#4]
版本: v2.5 - exe Package for Windows
症状: 线程无法正确停止, 即使已经抓取指定数量的图片之后仍会不断抓取(不产生新的图片)

**Comment by ImFatFish** [comment]
> 版本: v2.5 - exe Package for Windows
> 症状: 线程无法正确停止, 即使已经抓取指定数量的图片之后仍会不断抓取(不产生新的图片)

请您提供可执行文件目录下的"history.txt"以便进行问题复现

**Comment by PupilStudio** [comment]
> > 版本: v2.5 - exe Package for Windows
> > 症状: 线程无法正确停止, 即使已经抓取指定数量的图片之后仍会不断抓取(不产生新的图片)
> 
> 请您提供可执行文件目录下的"history.txt"以便进行问题复现

淦
我刚删掉
明天再复现

**Comment by ImFatFish** [comment]
> 删掉

神tm（不是

**Comment by ImFatFish** [comment]
（滑稽

**Comment by PupilStudio** [comment]
> 神tm（不是

我家长回来了awa

**Comment by ImFatFish** [comment]
> > 神tm（不是
> 
> 我家长回来了awa

QwQ

**Comment by PupilStudio** [comment]
> > > 神tm（不是
> > 
> > 
> > 我家长回来了awa
> 
> QwQ

awa

**Comment by PupilStudio** [comment]
没法复现了XD

**Comment by ImFatFish** [comment]
xswl

**Comment by ImFatFish** [comment]
XDDDD
